configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/corespeed-inc-dash%2Fmcp-store-client-18609dcbaa6dede438deca8d629eed24f004f7d64bfa08560154d05935d9f36e.yml
openapi_spec_hash: 2e3d7254ea9d56b11674cf93afbca61b
config_hash: 9ef9cbf47c6f6aa023dca849966abdbe
