configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/corespeed-inc-dash%2Fmcp-store-client-d79c3a81f9006c20d50798cbef3d901fe44a5c9207e117a4e1533fb65fdf3d95.yml
openapi_spec_hash: b1ce730c1e22b60a9b5ff59e00cc0a5c
config_hash: 1dd23c0a6b0f0ffdf2b23317f1fe8fbe
