configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/corespeed-inc-dash%2Fmcp-store-client-29dcca552446ce66a81dbaeef5d3f741eacc94f58527a8df12b142cd5dbf330b.yml
openapi_spec_hash: d6da5d9df66a5dacb9301535e97c702d
config_hash: a4dbc38c9eab81fe4764f15ff750d437
