configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/corespeed-inc-dash%2Fmcp-store-client-264b8960afd0d365b97459a2371eec3642364bf3b1fb72baae8f1a6c1ddc9175.yml
openapi_spec_hash: 3dd31c8470514ae37ea6d34b8e4c38c5
config_hash: 1dd23c0a6b0f0ffdf2b23317f1fe8fbe
